version: "3"
services:
    web:
        build: ./backend
        ports:
            - "8000:80"
        depends_on:
            - db
        volumes:
            - ./backend/app:/app
            - .env:/app/.env
        command: /start-reload.sh
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - ./db-data:/var/lib/postgresql/data
        env_file:
            - .env