version: "3"
services:
    web:
        build:
            args:
              INSTALL_DEV: true
        env_file:
            - .env.test
        command: /start.sh
    db:
        env_file:
            - .env.db
