version: "3"
services:
    web:
        build: ./backend
        ports:
            - "80:80"
        depends_on:
            - db
        volumes:
            - ./backend:/app
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - ./.data:/var/lib/postgresql/data
        env_file: .env