version: "3"
services:
    web:
        env_file:
            - .env.docker
        command: /start.sh
    db:
        env_file:
            - .env.db
        volumes:
            - ./db-data:/var/lib/postgresql/data
