version: "3"
services:
    web:
        env_file:
            - .env
        command: /start-reload.sh
    db:
        env_file:
            - .env
        volumes:
            - ./db-data:/var/lib/postgresql/data
