version: "3"
services:
    web:
        container_name: web
        build:
            args:
                INSTALL_DEV: ${INSTALL_DEV-false}
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - db
        volumes:
            - .:/app
        env_file:
            - .env.docker
    db:
        container_name: db
        image: postgres:latest
        ports:
            - "5432:5432"
        env_file:
            - .env.db
