version: "3"
services:
    web:
        container_name: web
        build:
            context: ./app
            args:
                INSTALL_DEV: ${INSTALL_DEV-false}
        ports:
            - "8000:80"
        depends_on:
            - db
        volumes:
            - ./app:/app
    db:
        container_name: db
        image: postgres:latest
        ports:
            - "5432:5432"
