"""Add expense table

Revision ID: 8e1220123fe0
Revises: 
Create Date: 2020-05-02 17:07:23.750989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8e1220123fe0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expense_description"),
        "expense",
        ["description"],
        unique=False,
    )
    op.create_index(op.f("ix_expense_id"), "expense", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expense_id"), table_name="expense")
    op.drop_index(op.f("ix_expense_description"), table_name="expense")
    op.drop_table("expense")
    # ### end Alembic commands ###
