"""test alembic

Revision ID: 61ec13301b39
Revises: 686a43334a8c
Create Date: 2024-01-06 18:11:16.194311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "61ec13301b39"
down_revision = "686a43334a8c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_expense_description", table_name="expense")
    op.drop_index("ix_expense_id", table_name="expense")
    op.drop_index("ix_expense_name", table_name="expense")
    op.drop_table("expense")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="expense_pkey"),
    )
    op.create_index("ix_expense_name", "expense", ["name"], unique=False)
    op.create_index("ix_expense_id", "expense", ["id"], unique=False)
    op.create_index(
        "ix_expense_description", "expense", ["description"], unique=False
    )
    # ### end Alembic commands ###
